#!/bin/bash

# Get the token first
SECRET="$GITHUB_TOKEN"
BODY='{"owner":"trieloff","repo":"as-a-bot"}'

echo "Getting fresh installation token..."
response=$(curl -sS -X POST https://as-bot-worker.minivelos.workers.dev/token \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -d "$BODY")

TOKEN=$(echo "$response" | jq -r '.token')

if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
  echo "Failed to get token"
  exit 1
fi

echo "✅ Token obtained"

# Post comment on PR #1
echo ""
echo "Posting comment on PR #1..."

comment_body=$(cat << 'COMMENT'
🤖 **GitHub App Token Broker Test**

Hello! This comment is being posted by the GitHub App using a token generated by the token broker deployed at https://as-bot-worker.minivelos.workers.dev

The token broker successfully:
- ✅ Authenticated the request with HMAC
- ✅ Created a valid GitHub App JWT
- ✅ Obtained an installation token from GitHub
- ✅ Enabled this automated comment

This demonstrates that the token broker is fully operational and can facilitate GitHub App actions!

---
*Posted via installation token obtained from the Cloudflare Worker token broker*
COMMENT
)

# Create JSON payload
json_payload=$(jq -n --arg body "$comment_body" '{body: $body}')

# Post the comment
curl -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/ai-ecoverse/as-a-bot/issues/1/comments" \
  -d "$json_payload" \
  -w "\nHTTP Status: %{http_code}\n" | jq '.'

